name: Deploy Hello Dogs app to AWS Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Unittest
      run: | 
        pip install -r requirements.txt
        python -m unittest discover -s tests

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log into Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get short SHA
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ secrets.AWS_REGISTRY }}
        REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ env.SHORT_SHA }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:latest
  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy to AWS Lambda
        run: |
          IMAGE_URI="${{ secrets.AWS_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest"

          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --image-uri $IMAGE_URI \
            --region ${{ secrets.AWS_REGION }}

  